defmodule Pearl.Catalog do
  @moduledoc """
  Portugal information catalog.
  """

  def universities do
    [
      "Universidade do Minho",
      "Universidade do Porto",
      "Universidade de Coimbra",
      "Universidade de Lisboa",
      "Universidade Nova de Lisboa",
      "Universidade de Aveiro",
      "Universidade da Beira Interior",
      "Universidade de Évora",
      "Universidade do Algarve",
      "Universidade de Trás-os-Montes e Alto Douro",
      "Universidade da Madeira",
      "Universidade dos Açores",
      "Universidade Aberta",
      "ISCTE - Instituto Universitário de Lisboa",
      "Instituto Politécnico de Lisboa",
      "Instituto Politécnico do Porto",
      "Instituto Politécnico de Coimbra",
      "Instituto Politécnico de Leiria",
      "Instituto Politécnico de Setúbal",
      "Instituto Politécnico de Viseu",
      "Instituto Politécnico de Santarém",
      "Instituto Politécnico de Viana do Castelo",
      "Instituto Politécnico de Castelo Branco",
      "Instituto Politécnico de Beja",
      "Instituto Politécnico de Bragança",
      "Instituto Politécnico da Guarda",
      "Instituto Politécnico de Portalegre",
      "Instituto Politécnico de Tomar",
      "Instituto Politécnico do Cávado e do Ave",
      "Universidade Católica Portuguesa",
      "Universidade Lusófona",
      "Universidade Lusíada",
      "Universidade Fernando Pessoa",
      "Universidade Europeia",
      "Universidade Autónoma de Lisboa",
      "Universidade Portucalense",
      "Universidade Atlântica",
      "Outra / Externo"
    ]
  end

  def cities do
  [
    "Agualva-Cacém",
    "Albufeira",
    "Alcobaça",
    "Almada",
    "Amadora",
    "Amarante",
    "Angra do Heroísmo",
    "Aveiro",
    "Barcelos",
    "Barreiro",
    "Beja",
    "Braga",
    "Bragança",
    "Caldas da Rainha",
    "Cascais",
    "Castelo Branco",
    "Chaves",
    "Coimbra",
    "Covilhã",
    "Câmara de Lobos",
    "Elvas",
    "Entroncamento",
    "Esposende",
    "Évora",
    "Fafe",
    "Faro",
    "Felgueiras",
    "Figueira da Foz",
    "Funchal",
    "Fátima",
    "Gondomar",
    "Guarda",
    "Guimarães",
    "Horta",
    "Ílhavo",
    "Lagos",
    "Lamego",
    "Leiria",
    "Lisboa",
    "Loulé",
    "Loures",
    "Machico",
    "Maia",
    "Marinha Grande",
    "Matosinhos",
    "Mirandela",
    "Montijo",
    "Odivelas",
    "Oeiras",
    "Olhão",
    "Ourém",
    "Ovar",
    "Paços de Ferreira",
    "Penafiel",
    "Peniche",
    "Peso da Régua",
    "Pombal",
    "Ponta Delgada",
    "Portalegre",
    "Portimão",
    "Porto",
    "Póvoa de Varzim",
    "Queluz",
    "Ribeira Grande",
    "Rio Tinto",
    "Santarém",
    "Santo Tirso",
    "Seixal",
    "Setúbal",
    "Sines",
    "Sintra",
    "São João da Madeira",
    "Tavira",
    "Tomar",
    "Torres Novas",
    "Torres Vedras",
    "Trofa",
    "Valongo",
    "Viana do Castelo",
    "Vila Franca de Xira",
    "Vila Nova de Famalicão",
    "Vila Nova de Gaia",
    "Vila Real",
    "Vila do Conde",
    "Viseu"
  ]
  |> Enum.sort()
  |> Kernel.++(["Outra"])
end
end
